django_chms/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    re_path(r'^$', views.front_page, name='home'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^families/', include(('families.urls', 'families'), namespace='families')),
    re_path(r'^cities_local/', include(('cities_local.urls', 'cities_local'), namespace='cities_local')),
    re_path(r'^groups/', include(('groups.urls', 'groups'), namespace='groups')),
    re_path(r'^events/', include(('events.urls', 'events'), namespace='events')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls))
            ]

events/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.EventListView.as_view(), name='event_list'),
        re_path(r'create_event/(?P<date>\d{4}-\d{2}-\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/(?P<start_time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/$', views.EventCreateView.as_view(), name='event_create'),
        #re_path(r'(?P<year>\d{4})-(?P<month>(0[1-9])|(1[0-2]))-(?P<day>(0[1-9])|([12][0-9])|(3[01]))/$', views.EventDailyListView.as_view(), name='event_daily'),
        #re_path(r'(?P<year>\d{4})-(?P<week>(0[1-9])|([1-4][0-9])(5[0-2]))w/$', views.EventWeeklyListView.as_view(), name='event_weekly'),
        re_path(r'(?P<year>\d{4})-(?P<month>0[1-9]|1[0-2])/$', views.EventMonthlyListView.as_view(), name='event_monthly'),
        #re_path(r'(?P<year>\d{4})/$', views.EventYearlyListView.as_view(), name='event_yearly'),
        re_path(r'delete_event_(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),
        re_path(r'edit_event_(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_edit'),
        re_path(r'(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
        ]

events/forms.py
#from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms
from django.contrib.admin import widgets                                       

from dateutil import rrule
from django.conf import settings
#from djangoformsetjs.utils import formset_media_js
from bootstrap_datepicker_plus.widgets import DateTimePickerInput

from .models import *
import pytz


FREQ_CHOICES = (
        (rrule.DAILY, 'Daily'),
        (rrule.WEEKLY, 'Weekly'),
        (rrule.MONTHLY, 'Monthly'),
        (rrule.YEARLY, 'Yearly'),
        )

EVENT_TYPE_CHOICES = (
        ('S', 'Simple'),
        ('R', 'Recurring Event'),
        )

WEEK_START = settings.WEEK_START_DAY

class EventForm(forms.ModelForm):
    #event_type = forms.ChoiceField(
    #        choices=EVENT_TYPE_CHOICES, 
    #        widget=forms.Select(attrs = {
    #            'onchange' : 'refresh();',
    #        }
    #        ),
    #    )
    #def __init__(self, *args, **kwargs):
    #    super(EventForm, self).__init__(*args, **kwargs)
    #    self.fields['event_type'].widget = forms.Select(attrs = {'onchange' : "alert('foo');"}, ) 
    class Meta:
        model = Event
        fields = ['name', 'location', 'group', 'event_type', 'description', 'creator']
        widgets = {'event_type': forms.Select(attrs = {'onchange' : 'javascript:selectEvent()', }) }
        #initial = {'event_type': 'S'}
        choices = {'event_type': EVENT_TYPE_CHOICES}
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['event_type'].initial = 'S'

#'javascript:handleClick(this);',

class OccurrenceForm(forms.ModelForm):
    class Meta:
        model = Occurrence
        fields = ('start_time', 'end_time', 'notes', 'all_day', 'multi_day')
        widgets = {
                'start_time': DateTimePickerInput(
                    options={'inline': True, 'stepping': 15}
                        ), #options={'format' : "YYYY-MM-DD HH:mm", 'stepping': 15, 'inline': True }), 
                'end_time': DateTimePickerInput(
                    options={'inline': True, 'stepping': 15}
                        ), #options={'format' : "YYYY-MM-DD HH:mm", 'stepping': 15, 'inline': True }), 
                    }
        #initial = {'start_time': start_time, 'end_time': end_time}
        #widgets = {'start_time': forms.widgets.DateTimeInput(attrs={'class':'timepicker'}), 
        #        'end_time': forms.widgets.DateTimeInput(attrs={'class':'timepicker'})
        #        }
    def __init__(self, *args, **kwargs):
        self.start_time = kwargs.pop('start_time', None)
        self.end_time = kwargs.pop('end_time', None)
        #if self.start_time:
        #    self.start_time = pytz.timezone(settings.TIME_ZONE).localize(self.start_time)
        #if self.end_time:
        #    self.start_time = pytz.timezone(settings.TIME_ZONE).localize(self.start_time)
        super(OccurrenceForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].initial = self.start_time
        self.fields['end_time'].initial = self.end_time
        self.fields['all_day'].initial = False 
        self.fields['multi_day'].initial = False 

        self.fields['start_time'].required = False
        self.fields['end_time'].required = False
        self.fields['notes'].required = False
        self.fields['all_day'].required = False 
        self.fields['multi_day'].required = False 
    #class Media(object):
    #    js = formset_media_js

OccurrenceFormset = forms.inlineformset_factory(
        Event, Occurrence,
        form=OccurrenceForm,
        extra=1,
     )

class RecurringEventForm(forms.Form):
    freq = forms.ChoiceField(
        required=False,
        #widget=forms.Select(attrs = {
        #    'onchange' : 'javascript:handleClick(this);',
        #    }
        #    ),
        choices=FREQ_CHOICES,
        label='Frequency',
    )
    start_time = forms.DateTimeField(
            widget=DateTimePickerInput(
                options={'format' : "YYYY-MM-DD HH:mm", 'stepping': 15, 'inline': True}
                )
            )
    duration = forms.DurationField(
            widget=forms.TextInput(
                attrs={'placeholder':'00:30'}
                )
            )
    until = forms.DateTimeField(widget=DateTimePickerInput(
                options={'format' : "YYYY-MM-DD HH:mm", 'stepping': 15, 'inline': True}
        )
        )
    #until = forms.DateField(widget=widgets.AdminDateWidget)

    def __init__(self, *args, **kwargs):
        super(RecurringEventForm, self).__init__(*args, **kwargs)

        self.fields['freq'].required = False
        self.fields['start_time'].required = False 
        self.fields['until'].required = False 
        self.fields['duration'].required = False 

    def add_occurrences(self, **kwargs):
        Event.add_occurrences(**kwargs)

events/views.py
from braces.views import PrefetchRelatedMixin
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db import transaction
from django.db.models import Prefetch, Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from extra_views import InlineFormSetFactory, CreateWithInlinesView, UpdateWithInlinesView
from extra_views.generic import GenericInlineFormSetView

from . import forms
from . import models

# Create your views here.

class EventListView(PrefetchRelatedMixin, ListView):
    model = models.Occurrence
    template_name = 'events/event_list.html'
    context_object_name = 'events'
    paginate_by = 10
    #ordering = ['start_time',]


    def get_context_data(self):
        context = super().get_context_data()
        context['church_name'] = settings.CHURCH_NAME
        return context

    def get_queryset(self):
        return self.model.objects.filter(start_time__date__gte=datetime.today()).order_by('start_time')


class EventYearlyListView(ListView):
    model = models.Occurrence
    context_object_name = 'events'
    template_name = "events/event_year_list.html"

    def get_context_data(self):
        context = super().get_context_data()
        context['year'] = self.kwargs['year']
        return context

class EventMonthlyListView(ListView):
    model = models.Occurrence
    context_object_name = 'events'
    template_name = "events/monthly_calendar.html"

    def get_context_data(self):
        context = super().get_context_data()
        context['calyear'] = self.kwargs['year']
        context['calmonth'] = self.kwargs['month']
        return context

    def get_queryset(self):
        # Queries the events in the Occurrence table that fall on the given month
        return self.model.objects.filter(Q(start_time__year=self.kwargs['year'],
            start_time__month=self.kwargs['month'])
            #|(Q(end_time__year=self.kwargs['year'],
            #end_time__month=self.kwargs['month']))
            )


class EventWeeklyListView(ListView):
    model = models.Occurrence
    context_object_name = 'events'
    template_name = "events/event_list.html"

    class Meta:
        ordering = ['start_time']

    def get_context_data(self):
        context = super().get_context_data()
        context['year'] = self.kwargs['year']
        context['week'] = self.kwargs['week']
        return context


class EventDailyListView(ListView):
    model = models.Occurrence
    context_object_name = 'events'
    template_name = "events/daily_events.html"

    def get_context_data(self):
        context = super().get_context_data()
        context['calyear'] = self.kwargs['year']
        context['calmonth'] = self.kwargs['month']
        context['calday'] = self.kwargs['day']
        context['from_time'] = settings.DEFAULT_DAY_BEGIN
        context['to_time'] = settings.DEFAULT_DAY_END
        context['delta'] = settings.DEFAULT_TIME_INTERVAL
        return context

    def get_queryset(self):
        # Queries the events in the Occurrence table that fall on the given day
        ## 1. that begin on that day
        ## 2. that end on the day
        ## 3. (to do) that begin before and end after that day
        return self.model.objects.filter(Q(start_time__year=self.kwargs['year'],
            start_time__month=self.kwargs['month'], 
            start_time__day=self.kwargs['day'])
            #|(Q(end_time__year=self.kwargs['year'],
            #end_time__month=self.kwargs['month'], 
            #end_time__day=self.kwargs['day']))
            )


class EventDetailView(DetailView, ):
    model = models.Event
    context_object_name = 'event'
    template_name = "events/event_detail.html"

class EventCreateView(LoginRequiredMixin, CreateView):
    model = models.Event
    form_class = forms.EventForm
 
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('events:event_list')

    def get_context_data(self, **kwargs):
        self.start_time = self.kwargs.get('start_time', None)
        self.duration = self.kwargs.get('duration', None)
        self.date = self.kwargs.get('date', None)
        if self.start_time:
            self.start_time = datetime.strptime(self.start_time, '%Y-%m-%dT%H:%M:%S')
        elif self.date:
            self.start_time = datetime.strptime(self.date, '%Y-%m-%d')
        
        context = super(EventCreateView, self).get_context_data(**kwargs)
        if 'post_occurrences' in self.request.POST:
            #context['occurrences'] = forms.OccurrenceFormset(self.request.POST,
            #       form_kwargs={'start_time': self.start_time, 'end_time': self.end_time})
            context['occurrences'] = forms.OccurrenceFormset(self.request.POST)
            context['recurring_events'] = None
            #context['occurrences'].fields['start_time'].required = True
            #context['occurrences'].fields['end_time'].required = True
            #context['occurrences'].fields['all_day'].required = True
        elif 'post_recurring' in self.request.POST:
            context['recurring_events'] = forms.RecurringEventForm(self.request.POST)
            context['recurring_events'].fields['freq'].required = True
            context['recurring_events'].fields['start_time'].required = True
            context['recurring_events'].fields['duration'].required = True
            context['recurring_events'].fields['until'].required = True
            context['occurrences'] = None
        else:
            context['occurrences'] = forms.OccurrenceFormset(form_kwargs={'start_time': self.start_time,
                 'end_time': self.start_time + timedelta(minutes=30)})
            context['recurring_events'] = forms.RecurringEventForm()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        #print(context)
        occurrences = context.get('occurrences', None)
        recurring_events = context.get('recurring_events', None)
        self.object = form.save()
        with transaction.atomic():
            if occurrences != None:
                if occurrences.is_valid():
                    occurrences.instance = self.object
                    print(occurrences)
                    occurrences.save()
                    #self.object.add_occurrences(**occurrences.cleaned_data)
                else:
                    print('occurence errors:')
                    for error in occurrences.errors:
                        print(error)
            elif recurring_events != None:
                if recurring_events.is_valid():
                    #self.object = form.save()
                    print(recurring_events.cleaned_data)
                    self.object.add_occurrences(**recurring_events.cleaned_data)
                else:
                    print('recurring_events errors:')
                    for error in recurring_events.errors:
                        print(error)


            ##    #context.update({'occurrences': occurrences})

        return super(EventCreateView, self).form_valid(form)

class OccurrenceInline(InlineFormSetFactory):
    fields = ('start_time', 'duration', 'notes', 'all_day', 'multi_day')
    #max_num = 1
    model = models.Occurrence

class EventUpdateView(LoginRequiredMixin, UpdateWithInlinesView):
    model = models.Event
    template_name = 'events/event_form.html'
    fields = ('name', 'location', 'group', 'description', 'creator')
    inlines = (OccurrenceInline,)


class EventDeleteView(DeleteView):
    model = models.Event
    success_url = reverse_lazy('events:event_list')

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(user=self.request.user)
        else:
            return self.model.objects.all()

events/templates/events/daily_events.html
{% extends "events/layout.html" %}
{% load event_extras %}
{% load static from staticfiles %}

{% block title %}Calendar{% endblock %}
{% block content %}
{{ block.super }}


<div id="calendar">
	{% if events %}
	    {% daily_calendar calyear calmonth calday from_time to_time delta events %}
	    {% for event in events %}
	    {{ event.name }}
	    {% endfor %}
   {% else %} 
   	 {% daily_calendar calyear calmonth calday from_time to_time delta %}
   {% endif %}
</div>

{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
	<h1>Delete {{ event.name }}?</h1> 
	
    <form method="POST">
        {% csrf_token %}
		<input type="submit" class="button" value="Delete"> <a href="{% url 'events:event_detail' pk=event.pk %}">Cancel</a>
	</form>
{% endblock %}

events/templates/events/event_detail.html
{% extends "layout.html" %}

{% block title %}{{ event.name }}{% endblock %}
{% block content %}
<article>
		<h2>{{ event.name }}</h2>

        <ul style="list-style-type:none">
        		{% if event.location %}
        			<li>{{ event.location }}</li>
        		{% endif %}
        		{% if event.group %}
        			<li>{{ event.group }}</li>
        			{% endif %}
        			<li>{{ event.description }}</li>
								</ul>
                                <h2>Occurrences</h2>
								<ul style="list-style-type:none">
                {% for occurrence in event.occurrence_set.all %}
                <li>{{ occurrence.start_time }} </li>
                {% endfor %}
								</ul>


    {% if user.is_authenticated %}
            <a href="{% url 'events:event_edit' pk=event.pk %}"
                class="button">Edit Event</a>
			<br>
            <a href="{% url 'events:event_delete' pk=event.pk %}"
                class="button">Delete Event</a>
        <hr>
    {% endif %}


</article>	

{% endblock %}

events/templates/events/event_form.html
{% extends "events/layout.html" %}
{% block title %} {{ form.instance.name|default:"New Event" }} {{ block.super }} {% endblock %}

{% block static %}
{% load event_extras %}
{% load humanize event_extras %}
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{# Load CSS and JavaScript #}
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/handle.click.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
    
    <script type="text/javascript">
    $(function() {
        $('.formset_row').formset({
                addText: 'Add occurrence',
                deleteText: 'Remove',
                prefix: 'occurrence_set',
            });
        })
         </script>

    <script type="text/javascript">
        function selectEvent() {
        var eventVal=document.getElementById("id_event_type").value;  

        if (eventVal == "R"){
            $('#Multiple').hide();
            $('#Recurring').show();
        } else
            {
            $('#Multiple').show();
            $('#Recurring').hide();
            }
        }
         </script>

{% endblock %}
{% block content %}

{{ recurring_events.media }}
{{ occurrences.media }}
<link rel="stylesheet" href="{% static 'css/layout.css' %}">

<div>
    <h1>{{ form.instance.name|default:"Enter a new Event" }}</h1>
        <form id="events_form" method="POST" action="">
        {{ occurrences.management_form }}
        {% csrf_token %}
        {% bootstrap_form form %}
        <div id="Multiple">
        <input type="submit" name="post_occurrences" value="Save"/> <a href="{% url 'events:event_list' %}">Cancel</a>

        {% if form.instance.event_type == "R" %}
        <p>Recurring</p>
        {% elif form.instance.event_type == "S" %}
        <p>Simple</p>
        {% endif %}
            <table class="table">
                {% for occur_form in occurrences.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in occur_form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <div style="position: relative"></div>
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in occur_form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in occur_form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                <ul style="list-style:none">
                                {{ field.errors.as_ul }}
                                </ul>
                                {{ field }}
                            </td>
                        {% endfor %}
                           {#	<input type="checkbox" value="All Day Event"/> #}
                    </tr>
					</div>
                {% endfor %}

                
            </table>

        </div>
        <div id="Recurring" style="display:none;">
        <input type="submit" name="post_recurring" value="Save"/> <a href="{% url 'events:event_list' %}">Cancel</a>

            <table>
            	<th>Recurring Event</th>
        			<tr id="test"><td>{{ recurring_events.freq }}</td>
        			</tr>
					<tr>
						<td>Begin Date: {{ recurring_events.start_time }}</td>
						<td id="hideOnClick">End Date: {{ recurring_events.until }}</td>        								
					</tr>
					<tr>
					<td></td>
               <td>
        				<label for="cb"><input id="cb" type="checkbox" onclick="handleClick(this);"/>No End Date</label>
					</td>
		        	</tr>
        			<tr><td>Duration: {{ recurring_events.duration }}</td></tr>
        			<tr></tr>
            </table>

		</div>
    <br>

    </form>
</div>


    {% endblock %}

events/templates/events/event_list.html
{% extends "events/layout.html" %}
{% load event_extras %}
{% load static from staticfiles %}

{% block title %}{{ church_name }} Event List{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Upcoming Events</h1>
    <div class="right">
	    <a href="{% url 'events:event_create' %}">New Event</a>
    </div>
    <table class="fam_list">
        <tr>
            <td>Time</td>
            <td>Duration</td>
            <td>Event Name</td>
            <td>Event Group</td>
        {% for event in events %}
	        <tr>
            <td>{{ event.start_time }}</td>
            <td>{{ event.get_duration_hm }}</td>
            <td><a href="{% url 'events:event_detail' pk=event.event.pk %}">{{ event.event.name }}</a></td>
            <td>{{ event.event.group }}</td>
	 </tr>
    {% endfor %}
    </table>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

events/templates/events/layout.html
{% extends "layout.html" %}

{% block title %}Events | {{ block.super }}{% endblock %}
{% block static %}{% endblock %}
{% block content %}
    {{ block.super }}
{% endblock %}

events/templates/events/monthly_calendar.html
{% extends "events/layout.html" %}
{% load event_extras %}
{% load static %}

{% block title %}Calendar{% endblock %}
{% block static %}
<link rel='stylesheet' href="{% static 'fullcalendar-5.3.2/lib/main.css' %}" />
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/handle.click.js' %}"></script>
<script src="{% static 'fullcalendar-5.3.2/lib/main.js' %}"></script>
{% endblock %}
{% block content %}
{{ block.super }}
<script type="text/javascript">

document.addEventListener('DOMContentLoaded', function() {
		let calendar = document.getElementById('{{ calendar.id }}
				)
$(document).ready(function() {
    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
        // put your options and callbacks here
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: {{ events|create_list|safe}},
      dayClick: function(date, jsEvent, view, resourceObj) {

        //alert('Date: ' + date.format());
        //alert('Resource ID: ' + resourceObj.id);
          window.location = "{% url 'events:event_create' %}" + date.format()
    }
    });

});
</script>
<div id='calendar'></div>


{% endblock %}