django_chms/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    re_path(r'^$', views.front_page, name='home'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^families/', include(('families.urls', 'families'), namespace='families')),
    re_path(r'^cities_local/', include(('cities_local.urls', 'cities_local'), namespace='cities_local')),
    re_path(r'^groups/', include(('groups.urls', 'groups'), namespace='groups')),
    re_path(r'^events/', include(('events.urls', 'events'), namespace='events')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls))
            ]

events/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.EventListView.as_view(), name='event_list'),
        re_path(r'create_event/(?P<date>\d{4}-\d{2}-\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/(?P<start_time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/$', views.EventCreateView.as_view(), name='event_create'),
        #re_path(r'(?P<year>\d{4})-(?P<month>(0[1-9])|(1[0-2]))-(?P<day>(0[1-9])|([12][0-9])|(3[01]))/$', views.EventDailyListView.as_view(), name='event_daily'),
        #re_path(r'(?P<year>\d{4})-(?P<week>(0[1-9])|([1-4][0-9])(5[0-2]))w/$', views.EventWeeklyListView.as_view(), name='event_weekly'),
        re_path(r'(?P<year>\d{4})-(?P<month>0[1-9]|1[0-2])/$', views.EventMonthlyListView.as_view(), name='event_monthly'),
        #re_path(r'(?P<year>\d{4})/$', views.EventYearlyListView.as_view(), name='event_yearly'),
        re_path(r'delete_event_(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),
        re_path(r'edit_event_(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_edit'),
        re_path(r'(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
        ]

groups/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.GroupListView.as_view(), name='group_list'),
        re_path(r'create_grouptype/$', views.GroupTypeCreateView.as_view(), name='grouptype_create'),
        re_path(r'grouptype/$', views.GroupTypeListView.as_view(), name='grouptype_list'),
        re_path(r'create_group/$', views.GroupCreateView.as_view(), name='group_create'),
        re_path(r'create_member/(?P<group_pk>\d+)$', views.MemberCreateView.as_view(), name='member_create'),
        re_path(r'delete_member_(?P<group_pk>\d+)_(?P<pk>\d+)/$', views.MemberDeleteView.as_view(), name='member_delete'),
        re_path(r'delete_group_(?P<pk>\d+)/$', views.GroupDeleteView.as_view(), name='group_delete'),
        re_path(r'edit_grouptype_(?P<pk>\d+)/$', views.GroupTypeUpdateView.as_view(), name='grouptype_edit'),
        re_path(r'edit_group_(?P<pk>\d+)/$', views.GroupUpdateView.as_view(), name='group_edit'),
        re_path(r'search/$', views.GroupSearchView.as_view(), name='group_search'), 
        re_path(r'grouptype/(?P<pk>\d+)/$', views.GroupTypeGroupListView.as_view(), name='grouptype_group_list'),
        re_path(r'(?P<pk>\d+)/$', views.GroupDetailView.as_view(), name='group_detail'),
        ]

groups/models.py
from django.db import models
from django.urls import reverse_lazy
from families.models import Member

# Create your models here.

class GroupType(models.Model):
    group_type = models.CharField(unique=True, max_length=35)
    def __str__(self):
        return self.group_type

class Group(models.Model):
    group_name = models.CharField(max_length=100)
    group_type = models.ForeignKey(GroupType, blank=True, null=True, on_delete=models.PROTECT)
    group_description = models.CharField(blank=True, max_length=255)
    group_members = models.ManyToManyField(Member, through='GroupMember')

    def __str__(self):
        return self.group_name

    def get_absolute_url(self):
        return reverse_lazy('groups:group_detail', kwargs={
            'pk': self.id,
            })

class MemRole(models.Model):
    class Meta:
        verbose_name_plural = 'Membership Roles'
    mem_role = models.CharField(max_length=35)
    def __str__(self):
        return self.mem_role

class GroupMember(models.Model):
    member = models.ForeignKey(Member, on_delete=models.PROTECT)
    group = models.ForeignKey(Group, on_delete=models.PROTECT)
    leader = models.BooleanField(default=False)
    member_role = models.ForeignKey(MemRole, blank=True, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return '%s: %s (%s)' % (self.group, self.member, self.member_role)

groups/views.py
from braces.views import PrefetchRelatedMixin
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.conf import settings
from . import models

# Create your views here.
class GroupListView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('groupmember_set',)
    model = models.Group
    context_object_name = 'groups'
    ordering = ['group_name']
    paginate_by = 10

    def get_context_data(self):
        context = super().get_context_data()
        context['church_name'] = settings.CHURCH_NAME
        return context


class GroupCreateView(LoginRequiredMixin, CreateView):
    fields = ('group_name', 'group_type', 'group_description')
    template_name = 'groups/group_form.html'
    success_url = reverse_lazy('groups:group_list')
    model = models.Group


class GroupDetailView(PrefetchRelatedMixin, DetailView):
    prefetch_related = ('groupmember_set',)
    model = models.Group
    template_name = 'groups/group_detail.html'


class GroupDeleteView(DeleteView):
    model = models.Group
    success_url = reverse_lazy('groups:group_list')

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(user=self.request.user)
        else:
            return self.model.objects.all()


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Group
    fields = ('group_name', 'group_type', 'group_description')


class GroupSearchView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('groupmember_set', )
    template_name = 'groups/group_list.html'
    model = models.Group
    context_object_name = 'groups'

    def get_queryset(self):
        term = self.request.GET.get('q')
        return self.model.objects.filter(Q(group_name__icontains=term)|Q(group_description__icontains=term)|Q(group_type__group_type__icontains=term)).distinct()


class GroupTypeListView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('group_set',)
    model = models.GroupType
    context_object_name = 'grouptypes'
    ordering = ['group_type']
    paginate_by = 10

    def get_context_data(self):
        context = super().get_context_data()
        context['church_name'] = settings.CHURCH_NAME
        return context


class GroupTypeCreateView(LoginRequiredMixin, CreateView):
    model = models.GroupType
    fields = ('group_type',)
    template_name = 'groups/grouptype_form.html'
    success_url = reverse_lazy('groups:grouptype_list')


class GroupTypeGroupListView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('group_set',)
    model = models.Group
    template_name = 'groups/grouptype_group_list.html'
    context_object_name = 'groups'
    def get_queryset(self):
        return self.model.objects.filter(group_type=self.kwargs['pk'])


#class GroupTypeDetailView(DetailView, SingleObjectMixin):
#    context_object_name = 'group_type'
#    template_name = 'families/grouptype_detail.html'


class GroupTypeUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'families/grouptype_form.html' 
    model = models.GroupType
    fields = ('group_type',)

class MemberCreateView(LoginRequiredMixin, CreateView):
    model = models.GroupMember
    fields = ('member', 'leader', 'member_role', 'group')
    template_name = 'groups/groupmember_form.html'

    #def get_queryset(self):
    #    return self.model.objects.filter(group__group=self.kwargs['group_pk'])

    def get_initial(self):
        initial = super().get_initial()
        initial['group'] = self.kwargs['group_pk']
        return initial

    def get_success_url(self):
        return reverse_lazy('groups:group_detail', kwargs={'pk': self.kwargs['group_pk']})


class MemberDeleteView(DeleteView):
    model = models.GroupMember

    def get_success_url(self):
        return reverse_lazy('groups:group_detail', kwargs={'pk': self.kwargs['group_pk']})

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(user=self.request.user)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['group_pk'] = self.kwargs['group_pk']
        return context

groups/templates/groups/group_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
	<h1>Delete {{ group_name.name }}?</h1> 
	
    <form method="POST">
        {% csrf_token %}
		<input type="submit" class="button" value="Delete"> <a href="{% url 'groups:group_detail' pk=group.pk %}">Cancel</a>
	</form>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "layout.html" %}

{% block title %}{{ group.group_name }}{% endblock %}
{% block content %}
<article>
		<h2>{{ group.group_name }}</h2>

        <ul style="list-style-type:none">
        			<li>{{ group.group_type }}</li>
        			<li>{{ group.group_description }}</li>
								</ul>


    {% if user.is_authenticated %}
            <a href="{% url 'groups:group_edit' pk=group.pk %}"
                class="button">Edit Group</a>
			<br>
            <a href="{% url 'groups:group_delete' pk=group.pk %}"
                class="button">Delete Group</a>
        <hr>
    {% endif %}

		<section>
				{% for group_member in group.groupmember_set.all %}
                        <h3><a href="{{ group_member__families.member.get_absolute_url }}">{{ group_member.member }}</a>: {{ group_member.member_role }}</h3>
                                    <a href="{% url 'groups:member_delete' pk=group_member.pk group_pk=group.pk %}">Remove</a>
                   
				{% endfor %}
		</section>
</article>	
 <a href="{% url 'groups:member_create' group_pk=group.pk %}" class="button">Add Member</a>
	<br>

        	<a href="{% url 'groups:group_list' %}">Back to list</a>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/layout.html' %}
{% load family_extras %}

{% load staticfiles %}

{% block title %} {{ form.instance.group_name|default:"New Group" }} {{ block.super }} {% endblock %}
{% block content %}
<div>
    <h1>{{ form.instance.group_name|default:"Enter a new group" }}</h1>
    <form method="POST" action="">
    <table class="formtable">
        {% csrf_token %}
        <tr><td>{{ form.group_name.label }}</td><td>{{ form.group_name }}</td><td></td></tr>
        <tr><td>{{ form.group_type.label }}</td><td>{{ form.group_type }}</td><td><a href="{% url 'groups:grouptype_create' %}">New Group Type</a></td></tr>
        <tr><td>{{ form.group_description.label }}</td><td>{{ form.group_description }}</td><td></td></tr>
        {{ form.media }}
        <tr><td>
        <input type="submit" class="button" value="Save"></td><td><a class="button" href="{% url 'groups:group_list' %}">Cancel</a></td>
        </td><td></td>
        </tr>
    </table>
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/layout.html" %}
{% load group_extras %}

{% block title %}{{ church_name }} Group List{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Group List</h1>
    <div class="right">
	    <a href="{% url 'groups:group_create' %}">New Group</a>
    </div>
    <table class="fam_list">
        {% for group in groups %}
	        <tr>
            <th><a href="{% url 'groups:group_detail' pk=group.pk %}">{{ group.group_name }}</a></th>
    <td><a href="{% url 'groups:grouptype_list' %}">{{ group.group_type }}</a></td>
	 </tr>
    {% endfor %}
    </table>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

groups/templates/groups/groupmember_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
	<h1>Remove {{ groupmember.member }} from {{ groupmember.group }}?</h1> 
	
    <form method="POST">
        {% csrf_token %}
		<input type="submit" class="button" value="Delete"> <a href="{% url 'groups:group_detail' pk=group_pk %}">Cancel</a>
	</form>
{% endblock %}

groups/templates/groups/groupmember_form.html
{% extends 'layout.html' %}

{% block title %} 
    {{ group }} New Group Member {{ block.super }} 
{% endblock %}

{% block content %}
    <div class="row">

            <h1>Add a New Group Member</h1>

        <form method="POST" action="">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="button" value="Save">
        </form>
    </div>
{% endblock %}

groups/templates/groups/grouptype_form.html
{% extends 'groups/layout.html' %}
{% load family_extras %}

{% load staticfiles %}

{% block title %} {{ form.instance.group_type|default:"New Group Type" }} {{ block.super }} {% endblock %}
{% block content %}
<div>
    <h1>{{ form.instance.group_type|default:"Enter a new group Type" }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save"><a href="{% url 'groups:grouptype_list' %}">Cancel</a>
    </form>
</div>
{% endblock %}

groups/templates/groups/grouptype_group_list.html
{% extends "groups/layout.html" %}
{% load group_extras %}
{% load static from staticfiles %}


{% block title %}{{ church_name }} Group List{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Group List</h1>
    <div class="right">
	    <a href="{% url 'groups:group_create' %}">New Group</a>
    </div>
    <table class="fam_list">
        {% for group in groups %}
	        <tr>
            <th><a href="{% url 'groups:group_detail' pk=group.pk %}">{{ group.group_name }}</a></th>
    <td>   
	{% for group_member in group.groupmember_set.all %}
		<a href="{{ group_member.member__member.get_absolute_url }}">{{ group_member.member }}</a>: {{ group_member.member_role }}
    {% endfor %}
     </td>
	 </tr>
    {% endfor %}
    </table>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

groups/templates/groups/grouptype_list.html
{% extends "groups/layout.html" %}
{% load group_extras %}
{% load static from staticfiles %}

{% block title %}{{ church_name }}groups by type{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Group Type List</h1>
    <div class="right">
	    <a href="{% url 'groups:grouptype_create' %}">New Type</a>
    </div>
    <table class="fam_list">
        {% for grouptype in grouptypes %}
	        <tr>
            <th><a href="{% url 'groups:grouptype_group_list' pk=grouptype.pk %}">{{ grouptype.group_type }}</a></th>
    <td>   
	{% for group in grouptype.group_set.all %}
    <tr>   
    <td>   
        <a href="{{ group.get_absolute_url }}">{{ group.group_name }}</a>
     </td>
	 </tr>
    {% endfor %}
    {% endfor %}
    </table>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

groups/templates/groups/layout.html
{% extends "layout.html" %}

{% block title %}Groups | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
	    <div class="right">
	    <form action="{% url 'groups:group_search' %}" method="GET">
            <input type="search" name="q">
			    <button type="button">
			    </button>
	    </form>
	    </div>
        <ul class="nav2">
            <li><a href="{% url 'groups:group_list' %}">List by Group</a><li>
            <li><a href="{% url 'groups:grouptype_list' %}">List by Type</a><li>
        </ul>
{% endblock %}