accounts/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^profile/$', views.profile_view, name='profile'),
        re_path(r'^logout/$', views.LogoutView.as_view(), name='logout'),
        re_path(r'^login/$', views.LoginView.as_view(), name='login'),
        re_path(r'signup/$', views.SignUpView.as_view(), name="signup"),
        ]

django_chms/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    re_path(r'^$', views.front_page, name='home'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^families/', include(('families.urls', 'families'), namespace='families')),
    re_path(r'^cities_local/', include(('cities_local.urls', 'cities_local'), namespace='cities_local')),
    re_path(r'^groups/', include(('groups.urls', 'groups'), namespace='groups')),
    re_path(r'^events/', include(('events.urls', 'events'), namespace='events')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls))
            ]

events/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.EventListView.as_view(), name='event_list'),
        re_path(r'create_event/(?P<date>\d{4}-\d{2}-\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/(?P<start_time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/$', views.EventCreateView.as_view(), name='event_create'),
        #re_path(r'(?P<year>\d{4})-(?P<month>(0[1-9])|(1[0-2]))-(?P<day>(0[1-9])|([12][0-9])|(3[01]))/$', views.EventDailyListView.as_view(), name='event_daily'),
        #re_path(r'(?P<year>\d{4})-(?P<week>(0[1-9])|([1-4][0-9])(5[0-2]))w/$', views.EventWeeklyListView.as_view(), name='event_weekly'),
        re_path(r'(?P<year>\d{4})-(?P<month>0[1-9]|1[0-2])/$', views.EventMonthlyListView.as_view(), name='event_monthly'),
        #re_path(r'(?P<year>\d{4})/$', views.EventYearlyListView.as_view(), name='event_yearly'),
        re_path(r'delete_event_(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),
        re_path(r'edit_event_(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_edit'),
        re_path(r'(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
        ]

families/urls.py
from django.urls import re_path

from . import views

#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
        re_path(r'^$', views.FamilyListView.as_view(), name='family_list'),
        re_path(r'^members/$', views.MemberListView.as_view(), name='member_list'),
        re_path(r'^addressbook$', views.family_list_as_pdf, name='addressbook'),
        re_path(r'edit_family/(?P<pk>\d+)/$', views.FamilyUpdateView.as_view(), name='family_edit'),
        re_path(r'delete_family_(?P<pk>\d+)/$', views.FamilyDeleteView.as_view(), name='family_delete'),
        re_path(r'(?P<family_pk>\d+)/(?P<member_pk>\d+)/$', views.MemberDetailView.as_view(), name='member_detail'),
        re_path(r'(?P<family_pk>\d+)/create_member/$', views.MemberCreateView.as_view(), name='member_create'),
        re_path(r'(?P<family_pk>\d+)/delete_member_(?P<pk>\d+)/$', views.MemberDeleteView.as_view(), name='member_delete'),
        re_path(r'(?P<family_pk>\d+)/edit_member_(?P<member_pk>\d+)/$', views.MemberUpdateView.as_view(), name='member_edit'),
        re_path(r'create_family/$', views.FamilyCreateView.as_view(), name='family_create'),
        re_path(r'search/$', views.FamilySearchView.as_view(), name='search'), 
        re_path(r'(?P<pk>\d+)/$', views.FamilyDetailView.as_view(), name='family_detail'),
        ]

groups/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.GroupListView.as_view(), name='group_list'),
        re_path(r'create_grouptype/$', views.GroupTypeCreateView.as_view(), name='grouptype_create'),
        re_path(r'grouptype/$', views.GroupTypeListView.as_view(), name='grouptype_list'),
        re_path(r'create_group/$', views.GroupCreateView.as_view(), name='group_create'),
        re_path(r'create_member/(?P<group_pk>\d+)$', views.MemberCreateView.as_view(), name='member_create'),
        re_path(r'delete_member_(?P<group_pk>\d+)_(?P<pk>\d+)/$', views.MemberDeleteView.as_view(), name='member_delete'),
        re_path(r'delete_group_(?P<pk>\d+)/$', views.GroupDeleteView.as_view(), name='group_delete'),
        re_path(r'edit_grouptype_(?P<pk>\d+)/$', views.GroupTypeUpdateView.as_view(), name='grouptype_edit'),
        re_path(r'edit_group_(?P<pk>\d+)/$', views.GroupUpdateView.as_view(), name='group_edit'),
        re_path(r'search/$', views.GroupSearchView.as_view(), name='group_search'), 
        re_path(r'grouptype/(?P<pk>\d+)/$', views.GroupTypeGroupListView.as_view(), name='grouptype_group_list'),
        re_path(r'(?P<pk>\d+)/$', views.GroupDetailView.as_view(), name='group_detail'),
        ]

templates/home.html
{% extends "layout.html" %}
{% load static %}

{% block title %}{{ church_name }}{% endblock %}

{% block content %}
<h1>{{ church_name }}</h1>
<h2>Church Management System</h2>
<div class="center">
<img src="{{ image }}" alt='Main image'>
</div>
{% endblock %}

templates/layout.html
{% load static %}
{% load humanize event_extras %}
<!doctype html>
{% this_year as year %}
{% this_month as month %}
<html>
  <head>
	  <title>{% block title %} {% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/layout.css' %}">
      {% block static %} {% endblock %}
  </head>
  <body>
  <div class="site-container">
	 <nav>
		 <ul class="nav">
			 <li class="nav"><a class="nav" href="{% url 'home' %}">Home</a></li>
			 <li class="nav"><a class="nav" href="{% url 'families:family_list' %}">Families</a></li>
			 <li class="nav"><a class="nav" href="{% url 'groups:group_list' %}">Groups</a></li>
			 <li class="nav"><a class="nav" href="{% url 'events:event_monthly' year=year month=month %}">Events</a></li>
             {% if not user.is_authenticated %}
			 <li class="nav-right"><a href="{% url 'accounts:login' %}">Login</a></li>
             {% else %}
             <li class="nav-right"><a href="{% url 'accounts:profile' %}">{{ user.username }}</a></li>
             <li class="nav-right"><a href="{% url 'accounts:logout' %}">Logout</a></li>
             {% endif %}
			</ul>
			
		</nav>
  </div>
		  {% block content %}{% endblock %}
  </body>
</html>

templates/suggestion_form.html
{% extends "layout.html" %}

{% block title %}Suggest an idea{% endblock %}

{% block content %}
<h1>Suggestions</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
{% endblock %}