django_chms/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    re_path(r'^$', views.front_page, name='home'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^families/', include(('families.urls', 'families'), namespace='families')),
    re_path(r'^cities_local/', include(('cities_local.urls', 'cities_local'), namespace='cities_local')),
    re_path(r'^groups/', include(('groups.urls', 'groups'), namespace='groups')),
    re_path(r'^events/', include(('events.urls', 'events'), namespace='events')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls))
            ]

events/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
        re_path(r'^$', views.EventListView.as_view(), name='event_list'),
        re_path(r'create_event/(?P<date>\d{4}-\d{2}-\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/(?P<start_time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})/$', views.EventCreateView.as_view(), name='event_create'),
        re_path(r'create_event/$', views.EventCreateView.as_view(), name='event_create'),
        #re_path(r'(?P<year>\d{4})-(?P<month>(0[1-9])|(1[0-2]))-(?P<day>(0[1-9])|([12][0-9])|(3[01]))/$', views.EventDailyListView.as_view(), name='event_daily'),
        #re_path(r'(?P<year>\d{4})-(?P<week>(0[1-9])|([1-4][0-9])(5[0-2]))w/$', views.EventWeeklyListView.as_view(), name='event_weekly'),
        re_path(r'(?P<year>\d{4})-(?P<month>0[1-9]|1[0-2])/$', views.EventMonthlyListView.as_view(), name='event_monthly'),
        #re_path(r'(?P<year>\d{4})/$', views.EventYearlyListView.as_view(), name='event_yearly'),
        re_path(r'delete_event_(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),
        re_path(r'edit_event_(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_edit'),
        re_path(r'(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
        ]

families/urls.py
from django.urls import re_path

from . import views

#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
        re_path(r'^$', views.FamilyListView.as_view(), name='family_list'),
        re_path(r'^members/$', views.MemberListView.as_view(), name='member_list'),
        re_path(r'^addressbook$', views.family_list_as_pdf, name='addressbook'),
        re_path(r'edit_family/(?P<pk>\d+)/$', views.FamilyUpdateView.as_view(), name='family_edit'),
        re_path(r'delete_family_(?P<pk>\d+)/$', views.FamilyDeleteView.as_view(), name='family_delete'),
        re_path(r'(?P<family_pk>\d+)/(?P<member_pk>\d+)/$', views.MemberDetailView.as_view(), name='member_detail'),
        re_path(r'(?P<family_pk>\d+)/create_member/$', views.MemberCreateView.as_view(), name='member_create'),
        re_path(r'(?P<family_pk>\d+)/delete_member_(?P<pk>\d+)/$', views.MemberDeleteView.as_view(), name='member_delete'),
        re_path(r'(?P<family_pk>\d+)/edit_member_(?P<member_pk>\d+)/$', views.MemberUpdateView.as_view(), name='member_edit'),
        re_path(r'create_family/$', views.FamilyCreateView.as_view(), name='family_create'),
        re_path(r'search/$', views.FamilySearchView.as_view(), name='search'), 
        re_path(r'(?P<pk>\d+)/$', views.FamilyDetailView.as_view(), name='family_detail'),
        ]

families/forms.py
from dal import autocomplete
from datetime import date
from django import forms

from . import models
from cities_local.models import Country, Region, City

class FamilyForm(forms.ModelForm):
    country = forms.ModelChoiceField(
            queryset=Country.objects.all(),
            widget=autocomplete.ModelSelect2(url='cities_local:country_autocomplete')
            )
    region = forms.ModelChoiceField(
            queryset=Region.objects.all(),
            widget=autocomplete.ModelSelect2(url='cities_local:region_autocomplete', forward=('country',))
            )
    city = forms.ModelChoiceField(
            queryset=City.objects.all(),
            widget=autocomplete.ModelSelect2(url='cities_local:city_autocomplete', forward=('Region',))
            )
    class Meta:
        model = models.Family
        #fields = ('user', 'family_name', 'address1', 'address2', 'city', 'postal_code', 'region', 'country', 'notes')
        fields = ['user',
                'family_name',
                'address1',
                'address2',
                'country',
                'region',
                'city',
                'postal_code',
                'notes',
                'image',
                ]
        widgets = {'image': forms.widgets.ClearableFileInput}

class MemberForm(forms.ModelForm):
    class Meta:
        model = models.Member
        fields = [
                'title',
                'first_name',
                'middle_name',
                'last_name',
                'suffix',
                'fam_member_type',
                'gender',
                'birth_date', 
                'marital_status', 
                'date_joined', 
                'occupation',
                'workplace', 
                'school',
                'work_address', 
                'notes'
                ]

        widgets = {'birth_date': forms.widgets.SelectDateWidget(years=[y for y in range(date.today().year, date.today().year-110, -1)]), 'date_joined': forms.widgets.SelectDateWidget(years=[y for y in range(date.today().year, date.today().year-110, -1)])}
        #fields = ('title', 'first_name', 'last_name', 'suffix', 'fam_member_type', 'gender', 'birth_date', 
        #        'marital_status', 'date_joined', 'occupation', 'workplace', 'work_address', 'school', 'notes')
MemberFormset = forms.modelformset_factory(
        models.Member,
        form = MemberForm,
        extra=2,
        )

FamilyMemberInlineFormset = forms.inlineformset_factory(
        models.Family,
        models.Member,
        fields = (
                'title',
                'first_name',
                'middle_name',
                'last_name',
                'suffix',
                'gender',
                'fam_member_type',
        ),
        formset=MemberFormset,
        max_num=2,
     )

families/views.py
from braces.views import PrefetchRelatedMixin
from dal import autocomplete
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.forms.models import modelform_factory
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.db.models import Prefetch, Q
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template
from django.urls import reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from itertools import chain
from model_utils.managers import InheritanceManagerMixin
from model_utils.managers import InheritanceQuerySet
import os
from subprocess import Popen, PIPE
import tempfile
from . import forms
from . import models
from cities_local.models import Country, Region, City
# Create your views here.

class FamilyListView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('member_set',)
    #self.model.objects.prefetch_related(Prefetch('member_set', queryset=models.Member.objects.select_subclasses(), to_attr='members'))
    model = models.Family
    context_object_name = 'families'
    ordering = ['family_name']
    paginate_by = 10

    def get_context_data(self):
        context = super().get_context_data()
        return context

    def get_queryset(self):
        #return super(FamilyListView, self).get_queryset(request).select_subclasses()
        return InheritanceQuerySet(self.model).select_subclasses()

def family_list_as_pdf(request):
    families = models.Family.objects.all()
    families_member_related = families.prefetch_related('families_member_related')

    template = get_template('families/addressbook.tex')
    rendered_tpl = template.render({'families':families, 'member_set': families_member_related, 'media_root': settings.MEDIA_ROOT, 'church_name': settings.CHURCH_NAME}).encode('utf-8')
    # Python3 only. For python2 check out the docs!
    with tempfile.TemporaryDirectory() as tempdir:  
        # Create subprocess, supress output with PIPE and
        # run latex twice to generate the TOC properly.
        # Finally read the generated pdf.
        for i in range(2):
            process = Popen(
                ['pdflatex', '-output-directory', tempdir],
                stdin=PIPE,
                stdout=PIPE,
            )
            out, err = process.communicate(rendered_tpl)
            print(out, err)
        with open(os.path.join(tempdir, 'texput.pdf'), 'rb') as f:
            pdf = f.read()
    r = HttpResponse(content_type='application/pdf')  
    r['Content-Disposition'] = 'attachment; filename=texput.pdf'
    r.write(pdf)
    return r

class FamilyDetailView(PrefetchRelatedMixin, DetailView):
    context_object_name = 'family'
    prefetch_related = ('member_set',)
    model = models.Family
    template_name = 'families/family_detail.html'


    #def get_context_data(self, **kwargs):
    #    context = super(FamilyDetailView, self).get_context_data(**kwargs)
    #    #context['children'] = [member for member in prefetch_related['member_set'] if member.child == True]
    #    #context['adults'] = [member for member in prefetch_related['member_set'] if member.child == False]
    #    return context



class FamilyCreateView(PermissionRequiredMixin, CreateView):
    #fields = ('user', 'family_name', 'address1', 'address2', 'city', 'postal_code', 'region', 'country', 'notes')
    permission_required = 'is_staff'
    template_name = 'families/family_form.html'
    form_class = forms.FamilyForm
    success_url = reverse_lazy('families:family_list')
    #class Meta:
    #    model = models.Family

    #form_class =  modelform_factory(models.Family,
    #    fields = ('user', 'family_name', 'address1', 'address2', 'postal_code', 'country', 'region', 'city', 'notes'),
    #    widgets = {'country': autocomplete.ModelSelect2(url='cities_local:country_autocomplete'),
    #        'region': autocomplete.ModelSelect2(url='cities_local:region_autocomplete', forward=['country']),
    #        'city': autocomplete.ModelSelect2(url='cities_local:city_autocomplete', forward=['country', 'region']),
    #        }
    #    )

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.pk
        initial['country'] = Country.objects.get(name=settings.DEFAULT_COUNTRY).pk
        initial['region'] = Region.objects.get(name=settings.DEFAULT_REGION).pk
        initial['city'] = City.objects.get(name=settings.DEFAULT_CITY).pk
        return initial


class FamilyDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'is_staff'
    model = models.Family
    success_url = reverse_lazy('families:family_list')

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(user=self.request.user)
        else:
            return self.model.objects.all()


class FamilyUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Family
    template_name = 'families/family_form.html'
    #fields = ('user', 'family_name', 'address1', 'address2', 'postal_code', 'country', 'region', 'city', 'notes')
    form_class = forms.FamilyForm
    #def get_object(self):
    #    return self.request.user
    #pk_url_kwarg = 'pk'

    def get_success_url(self):
        return reverse_lazy('families:family_detail', kwargs={'pk': self.kwargs['pk'] })

    #def get_context_data(self):
    #    context = super().get_context_data()
    #    context['pk'] = self.kwargs['pk']
    #    return context

class FamilySearchView(PrefetchRelatedMixin, ListView):
    prefetch_related = ('member_set',)
    ordering = ['family_name']
    template_name = 'families/family_list.html'
    model = models.Family
    context_object_name = 'families'

    def get_queryset(self):
        term = self.request.GET.get('q')
        return self.model.objects.filter(Q(family_name__icontains=term)|Q(member__first_name__icontains=term)).distinct()


class MemberListView(ListView):
    model = models.Member
    #members = model.objects.all().select_subclasses()
    context_object_name = 'members'
    ordering = ['last_name']
    paginate_by = 10

    def get_context_data(self):
        context = super().get_context_data()
        context['church_name'] = settings.CHURCH_NAME
        return context


class MemberDetailView(DetailView, SingleObjectMixin):
    model = models.Member
    context_object_name = 'member'
    template_name = 'families/member_detail.html'
    pk_url_kwarg = 'member_pk'

    def get_queryset(self):
        return models.Member.objects.select_related('family').filter(family_id=self.kwargs['family_pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member = self.model.objects.get(pk=self.kwargs['member_pk'])
        context['member_pk'] = self.kwargs['member_pk']
        context['family_pk'] = self.kwargs['family_pk']
        context['age'] = member.age()
        return context


class MemberCreateView(LoginRequiredMixin, CreateView):
    model = models.Member
    template_name = 'families/member_form.html'
    form_class = forms.MemberForm

    def get_success_url(self):
        return reverse_lazy('families:family_detail', kwargs={'pk': self.kwargs['family_pk']})

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.pk
        initial['last_name'] = models.Family.objects.get(pk=self.kwargs['family_pk']).family_name
        return initial

    def get_context_data(self):
        context = super().get_context_data()
        context['family_pk'] = self.kwargs['family_pk']
        return context

    def form_valid(self, form):
        form.instance.family_id = self.kwargs['family_pk']
        return super(MemberCreateView, self).form_valid(form)

class MemberDeleteView(DeleteView):
    model = models.Member
    def get_success_url(self):
        return reverse_lazy('families:family_detail', kwargs={'pk': self.kwargs['family_pk']})

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(user=self.request.user)
        else:
            return self.model.objects.all()


class MemberUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'families/member_form.html' 
    model = models.Member
    fields = ('title', 'first_name', 'last_name', 'suffix', 'fam_member_type', 'gender', 'birth_date', 'marital_status', 'date_joined', 'occupation', 'workplace', 'work_address', 'school', 'notes')
    pk_url_kwarg = 'member_pk'

    def get_success_url(self):
        return reverse_lazy('families:member_detail', kwargs={'family_pk': self.kwargs['family_pk'], 'member_pk': self.kwargs['member_pk'] })

    def get_context_data(self):
        context = super().get_context_data()
        context['family_pk'] = self.kwargs['family_pk']
        return context

families/templates/families/family_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
	<h1>Delete {{ family.name }}?</h1> 
	
    <form method="POST">
        {% csrf_token %}
		<input type="submit" class="button" value="Delete"> <a href="{% url 'families:family_detail' pk=family.pk %}">Cancel</a>
	</form>
{% endblock %}

families/templates/families/family_detail.html
{% extends "layout.html" %}
{% load humanize family_extras %}

{% block title %}The {{ family.family_name }} Family{% endblock %}
{% block content %}
<article>
		<h2>The {{ family.family_name }} Family</h2>
		<table style="width:100%">
				<tr>
				<td>
						<div>
								<ul style="list-style-type:none">
        			<li>{{ family.address1 }}</li>
        			<li>{{ family.address2 }}</li>
					<li>{{ family.city }}</li>
        			<li>{{ family.postal_code }}</li>
        			<li>{{ family.region }}</li>
        			<li>{{ family.country }}</li>
								</ul>
						</div>
				</td>
						<td>
								{% if family.image_sm %}
							<img src="{{ family.image_sm.url }}" alt="{{ family.family_name }} Family Photo" width="300">
								{% else %}
							<img src="media/photos/family.png" alt="{{ family.family_name }} Family Photo" width="300">
								{% endif %}
						</td>
			</table>
        {{ family.notes|markdown_to_html}}
    {% if user.is_authenticated %}
            <a href="{% url 'families:family_edit' pk=family.pk %}"
                class="button">Edit Family Data</a>
			<br>
            <a href="{% url 'families:family_delete' pk=family.pk %}"
                class="button">Delete Family</a>
        <hr>
    {% endif %}

		        <table class="fam_list">
				{% for adult in family.get_adults %}
                <tr>
                <td>
                    <h3>
                    <a href="{{ adult.get_absolute_url }}">{{ adult.first_name }}</a> 
                    {% if adult.last_name != family.family_name %}
					    {{ adult.last_name }}
                    {% endif %}
                    </h3>
                </td> 
                <td class="right"><a href="{% url 'families:member_edit' member_pk=adult.pk family_pk=family.pk %}">Edit</a>  <a href="{% url 'families:member_delete' pk=adult.pk family_pk=family.pk %}">Remove</a> </td>
                </tr>
				{% endfor %}
				{% for child in family.get_children %}
                <tr>
                    <td>
                    <h3>
                        <a href="{{ child.get_absolute_url }}">{{ child.first_name }} </a> 
                    {% if child.last_name != family.family_name %}
					    {{ child.last_name }}
                    {% endif %}
                    </h3>
                        </td>
                <td class="right"><a href="{% url 'families:member_edit' member_pk=child.pk family_pk=family.pk %}">Edit</a>  <a href="{% url 'families:member_delete' pk=child.pk family_pk=family.pk %}">Remove</a> </td>
                </tr>
				{% endfor %}
		        </table>


    </article>
    {% if user.is_authenticated %}
            <a href="{% url 'families:member_create' family_pk=family.pk %}" class="button">Add Member</a>
	<br>
    {% endif %}
	<a href="{% url 'families:family_list' %}">Back to list</a>
{% endblock %}

families/templates/families/family_form.html
{% extends 'families/layout.html' %}
{% load family_extras %}

{% block title %} 
{{ family }} {{ form.instance.family_name|default:"New Family" }} {{ block.super }} 
{% endblock %}
{% block content %}
<div>
    <h1>{{ form.instance.family_name|default:"Enter a new family" }}</h1>
    <form method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {% if request.user.is_staff %}
        {{ form.user }}
        {% endif %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit" class="button" value="Save"><a href="{% url 'families:family_list' %}">Cancel</a>
    </form>
</div>
{% endblock %}

families/templates/families/family_list.html
{% extends "families/layout.html" %}
{% load family_extras %}
{# {% block static %}<link rel="stylesheet" href="{% static 'family/css/family.css' %}">{% endblock %} #}
{% block title %}Directory{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Directory</h1>
    <div class="right">
	    <a href="{% url 'families:family_create' %}">New Family</a>
    </div>
    <table class="fam_list">
	 <thead>
    <tr>
      <th>Family Name</th>
      <th colspan="2">Adults</th>
      <th>Children</th>
    </tr>
  </thead>
        {% for family in families %}
	<tr>
            <td>
                <header><a href="{% url 'families:family_detail' pk=family.pk %}">{{ family.family_name }}</a></header>
            </td>


	{% for member in family.get_adults %}
	<td> <a href="{{ member.get_absolute_url }}">{{ member.first_name }}</a></td> 

    {% endfor %}
	<td>
	{{ family.get_children_names|join_by }}
	<!-- {{ member.first_name }} -->

	</td>
    {% endfor %}
    </table>
	<br>
    <a href="{% url 'families:addressbook' %}">Create Addressbook PDF<a>
    <br>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

families/templates/families/family_list_tables.html
{% load render_table from django_tables2 %}
{% load static from staticfiles %}

{% block title %}Families{% endblock %}
{% block static %}<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />{% endblock %}
{% block content %}
    <h1>Families</h1>
 {% render_table families %}
{% endblock %}

families/templates/families/family_nav.html
{% for family in families %}

<div> <a href="{% url 'families:detail' pk=family.id %}">{{ family.family_name }}</a></div> 
{% endfor %}

families/templates/families/layout.html
{% extends "layout.html" %}

{% block title %}Families | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
	    <div class="right">
	    <form action="{% url 'families:search' %}" method="GET">
            <input type="search" name="q">
			    <button type="button">
			    </button>
	    </form>
	    </div>
                <ul class="nav2">
            <li><a href="{% url 'families:family_list' %}">List by Family</a><li>
            <li><a href="{% url 'families:member_list' %}">List by Member</a><li>
        </ul>
{% endblock %}

families/templates/families/member_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
	<h1>Delete {{ member.first_name }}?</h1> 
	
    <form method="POST">
        {% csrf_token %}
		<input type="submit" class="button" value="Delete"> <a href="{% url 'families:family_detail' pk=member.family.pk %}">Cancel</a>
	</form>
{% endblock %}

families/templates/families/member_detail.html
{% extends "layout.html" %}
{% load family_extras %}

{% block title %} {{ member.last_name }},{{ member.first_name }} {% endblock %}

{% block content %}
    <article>
        <h2>{{ member.family.family_name }}</h2>
        <h3>{{ member.first_name }} {{ member.last_name }}</h3>
        <h4>{{ member.birth_date }}</h3>
        {% if age %}
            <p>Age: {{ age }}</p>
        {% endif %}
    </article>

{% if user.is_authenticated %}
    <hr>
{% endif %}
<ul class="nav">
    <li><a href="{% url 'families:family_list' %}">Browse Families</a></li>
    <li><a href="{{ member.family.get_absolute_url }}">{{ member.family }} Family</a></li>
    <li><a href="{% url 'families:member_edit' member_pk=member_pk family_pk=family_pk %}">Edit Family Member</a></li>
</ul>
					
{% endblock %}

families/templates/families/member_form.html
{% extends 'layout.html' %}

{% block title %} 
    {{ family }} {{ form.instance.first_name|default:"New Member" }} {{ block.super }} 
{% endblock %}

{% block content %}
    <div class="row">
        <h1>{{ form.instance.first_name }} {{ form.instance.last_name|default:"Add a New Member" }}</h1>
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button" value="Save"><a href="{% url 'families:family_detail' pk=family_pk %}">Cancel</a>
        </form>
    </div>
    </div>
{% endblock %}

families/templates/families/member_list.html
{% extends "families/layout.html" %}
{% load group_extras %}
{% load static from staticfiles %}

{% block title %}{{ church_name }} Member List{% endblock %}

{% block content %}
{{ block.super }}
    <h1>Member List</h1>
    <table class="fam_list">
        {% for member in members %}
	        <tr>
                <th><a href="{% url 'families:member_detail' family_pk=member.family.pk member_pk=member.pk %}">{{ member.last_name }}, {{ member.first_name }}</a></th>
	          </tr>
        {% endfor %}
    </table>
    <br>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}